### PR TITLE
Remove IDEPlaygroundEditor for Xcode 8.3 support

### PR DESCRIPTION
**Pull request by keith**
This no longer exists in the release version of Xcode 8.3. With this
change XVim compiles and works in 8.3.

### CODE REVIEW

**Comment by tmm1** [comment]
:+1:

**Comment by Ronaldoh1** [comment]
Also getting a build error on 8.3 😢. Hope this fixes it.

**Comment by keith** [comment]
@Ronaldoh1 please check out this branch and verify.

**Comment by Ronaldoh1** [comment]
@keith Money! :money - thanks man. Good stuff. 👍

**Comment by isfang** [comment]
thanks, it's so kind of you!

**Comment by casatwy** [comment]
THXXXXX! life saver!!!!

**Comment by sh8** [comment]
THX!!!!

**Comment by huluqiu** [comment]
THX!!!

**Comment by imzoer** [comment]
THX!!!

**Pull request merged**
