### PR TITLE
Implement #458

### PR DESCRIPTION
**Pull request by hmuronaka**
Implement

:highlight Search guibg=#FF0000
:highlight Search guibg=blue

### CODE REVIEW

**Comment by keith** [comment]
Could this be adapted to work for setting the `guifg` as well? I tried to do this locally but it looks like those colors got overwritten.

**Comment by hmuronaka** [comment]
I did it, too. but It didn't work.

```obj-c
XVimOptions* options = [[XVim instance] options];
NSColor* highlightColor = options.highlight[@"Search"][@"guibg"];
NSColor* highlightTextColor = options.highlight[@"Search"][@"guifg"];
    
// Add highlight
for( NSTextCheckingResult* result in self.foundRanges){
  [self.layoutManager addTemporaryAttribute:NSBackgroundColorAttributeName value:highlightColor forCharacterRange:result.range];

  [self.layoutManager removeTemporaryAttribute:NSForegroundColorAttributeName forCharacterRange:result.range];
  [self.layoutManager addTemporaryAttribute:NSForegroundColorAttributeName value:highlightTextColor forCharacterRange:result.range];
}
```

**Comment by superarts** [comment]
Any idea why adding `set highlight Search guibg=blue` to `.xvimrc` doesn't work please?

**Comment by superarts** [comment]
The command works for me in `Xcode`, but may I ask why it doesn't work if I put `set highlight Search guibg=blue` in `.xvimrc` please?

**Pull request merged**
