### PR TITLE
Ex range command improvements

### PR DESCRIPTION
**Pull request by brucehappy**
## Known Issues Fixed:
* #718 (named marks in ex range)
* #700 (ex copy feature request)

## Improvements:
1. named marks supported in ex ranges
2. swapping backwards ex range
3. change . to use insertion point instead of selection begin
4. ex yank implemented
5. ex delete implemented
6. ex copy implemented
7. ex move implemented
8. ex shift left and right implemented
9. updated Feature List with Ex range and range command information

### CODE REVIEW

**Comment by brucehappy** [comment]
@JugglerShu , just checking on this pull request.  Do I need to rebase this against the develop branch in order to get it considered for inclusion?  Or is there something else amiss with this?

Thanks

**Comment by JugglerShu** [comment]
Thank you for the PR. Yes, please PR to develop branch.
And also, please understand that current develop branch is buggy and I currently only accept the bug fixes for the branch. So I cannot merge your PR immediately. (Maybe after some work on the branch, I'll merge yours.)

**Comment by brucehappy** [comment]
Ok, PR #735 created against develop.  Closing this PR.

**Comment by brucehappy** [comment]
I will leave my original master based feature branch open until my develop based feature branch has been merged into develop, and develop stabilizes.

**Pull request closed without merging**
