### PR TITLE
Hotfix for issue #251

### PR DESCRIPTION
**Pull request by squarefrog**
This is a hotfix for issue #251.

I'm unable to get the crash to happen while running tests, so I've had to manually test this using the following steps, using the latest `develop` branch in Xcode 7.3:

1. enter any file
2. hit `gg` to move to beginning of file
3. `V` to enter visual mode
4. hit `G` to move to the end of the file
5. hit `cmd+/` to comment the selected lines (every line in the file)
6. hit `esc` to exit visual mode
7. hit `gg` to move to beginning of file
8. `V` to enter visual mode
9. hit `G` to move to the end of the file
10. hit `cmd+/` to uncomment the selected lines
11. Xcode crashes with an out of bounds error

I experienced this crash when trying to delete a range towards the end of a file, but I'm unable to reproduce in the test environment, perhaps it only occurs when the file is reasonably large.

Before this commit there were 5 failing tests:

before

After this commit, the same 5 tests fail so I'm confident there are no regressions:

after

### CODE REVIEW

**Comment by JugglerShu** [comment]
Can you add a test case to reproduce the crash? (That should be merged together not to reproduce this again)

**Comment by squarefrog** [comment]
I tried to write a suitable test case, but the issue is the test doesn't seem to crash when running in the test environment.

**Comment by squarefrog** [comment]
@JugglerShu with a little bit of extra effort I managed to produce a test that proves the fix. It's now ready to merge.

If you'd like to test this, comment out the new lines in `NSTextView+VimOperation.m`, then run the tests. An exception will be raised. Now uncomment out the lines and retest, and everything works. :+1:

**Comment by JugglerShu** [comment]
Thanks for your great work!

**Pull request merged**
