### PR TITLE
Fix #776 Shift+O crash

### LINKED ISSUE #776: Shift+O on the first line of an empty file crashes Xcode
Shift+O on the first line of an empty file crashes Xcode

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22243934-shift-o-on-the-first-line-of-an-empty-file-crashes-xcode?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pebble8888**
All tests has passed.

### CODE REVIEW

**Comment by JugglerShu** [comment]
Please ad test case to prohibit regression of this issue. (Write test case that cause the crash when this PR is not applied).

**Comment by pebble8888** [comment]
I have added the test cause crash.

**Comment by JugglerShu** [comment]
Thank you.

**Comment by Arthaey** [comment]
How often are updates available via Alcatraz?

**Comment by JugglerShu** [comment]
I usually don't consider about Alcatraz. I don't know how they're managing XVim plugin, either.
I think that question should be asked in Alcatraz issue page.

**Comment by Arthaey** [comment]
Turns out, Alcatraz automatically updates each time Xcode is launched, so we're good! :) supermarin/Alcatraz#326

**Pull request merged**
