### PR TITLE
Fix #769 'cc' and 'S' auto indent issue

### LINKED ISSUE #769: 'S' and 'cc' should auto-indent
A simple workaround is just to map 'S' and 'cc' to 'ddO' or something similar, but this should work out of the box, as it does in vim.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/20700371-s-and-cc-should-auto-indent?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ooopscc**
This should fix the auto indent issue.

I just read this part of source code, and `-[XVimDeleteEvaluator motionFixed:]` is the only caller of `-xvim_change:` , so this change may not affect other functions in my opinion.

### CODE REVIEW

**Comment by JugglerShu** [comment]
Please write test case for this to merge. Thank you.

**Comment by ooopscc** [comment]
It may fail in few cases, don't merge for now

**Comment by ooopscc** [comment]
Done. No failed cases anymore.

**Comment by Francescu** [comment]
:+1:

**Pull request merged**
