### PR TITLE
Prevent "too many nested groupings" xcode crash on undo

### PR DESCRIPTION
**Pull request by jasonmay**
When 954f200 was introduced, I don't think it accounted for the fact that the undo handlers would get triggers for `r` as well as `R`, which I believe resulted in #817 being reported.

I unfortunately was not able to test. I added `set debug` to my config, restarted Xcode many times, and looked all over the menu for `XVim -> Run Test` but didn't see anything. I'd be more than happy if someone who can run the tests could piggyback on this PR and write a test and run it on my behalf.

Thanks!

### CODE REVIEW

**Comment by squarefrog** [comment]
The test menu can be found in `Editor > XVim > Run Test`

**Comment by jasonmay** [comment]
Thanks @squarefrog. Test has been added. That test fails with "exception raised" without the fix.

**Comment by jasonmay** [comment]
To expand on the new change, the test showed that it works just fine for any type of replace. I was throwing the baby out with the bathwater with my initial fix, but it's only for newlines that it crashed on, so I handle that specific case instead.

**Comment by squarefrog** [comment]
:+1: glad you were able to narrow down the fix!

**Comment by jasonmay** [comment]
I am cherry-picking changes from #770 and adding tests (and fixing the edge cases mentioned). To save on hassle, how do I get the tests to see the updated code without having to restart Xcode every time?

**Comment by jasonmay** [comment]
Closing in favor of #960

**Pull request closed without merging**
