### PR TITLE
Use codesign --remove-signature

### PR DESCRIPTION
**Pull request by JessThrysoee**

### CODE REVIEW

**Comment by squarefrog** [comment]
This makes Xcode 8 GM crash on launch for me.

```
Process:               Xcode [26873]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               ???
Build Info:            IDEFrameworks-11246000000000000~3
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [26873]
User ID:               501

Date/Time:             2016-09-12 10:56:48.471 +0100
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        E1D21958-19E9-4091-E97E-EF99AEDDA9F7

Sleep/Wake UUID:       D812099E-CBFB-4075-86C5-0DD5C3244FDD

Time Awake Since Boot: 230000 seconds
Time Since Wake:       8400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000103f1a010
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:
-0 sec           	CODE SIGNING: cs_invalid_page(0x103f1a000): p=26873[Xcode] final status 0x3006a00, denying page sending SIGKILL
-0 sec           	CODE SIGNING: process 26873[Xcode]: rejecting invalid page at address 0x103f1a000 from offset 0x0 in file "/Applications/Xcode.app/Contents/MacOS/Xcode" (cs_mtime:1472438496.0 != mtime:1473674137.0) (signed:1 validated:1 tainted:1 wpmapped:0 slid:0)
-21 sec          	CODE SIGNING: cs_invalid_page(0x10f58a000): p=26855[Xcode] final status 0x3006a00, denying page sending SIGKILL
-21 sec          	CODE SIGNING: process 26855[Xcode]: rejecting invalid page at address 0x10f58a000 from offset 0x0 in file "/Applications/Xcode.app/Contents/MacOS/Xcode" (cs_mtime:1472438496.0 != mtime:1473674137.0) (signed:1 validated:1 tainted:1 wpmapped:0 slid:0)

VM Regions Near 0x103f1a010:
--> mapped file            0000000103f1a000-0000000103f1b000 [    4K] r-x/rwx SM=COW  -
    mapped file            0000000103f1b000-0000000103f1c000 [    4K] rw-/rwx SM=COW  -

Thread 0 Crashed:
0   dyld                          	0x00007fff6bca4202 dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 396
1   dyld                          	0x00007fff6bca4036 _dyld_start + 54

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000103f1a000  rbx: 0x00007fff5bce5d10  rcx: 0x8800bcd1e9f1e102  rdx: 0x00000000000000f1
  rdi: 0x00007fff5bce5fab  rsi: 0x00007fff6bccd410  rbp: 0x00007fff5bce5c50  rsp: 0x00007fff5bce5bf0
   r8: 0x000000000000003d   r9: 0x00000000000003e0  r10: 0x000000000000000c  r11: 0x0000000000000202
  r12: 0x00007fff6bca3520  r13: 0x000000000000000e  r14: 0x00007fff6bca36c0  r15: 0x000000000000000e
  rip: 0x00007fff6bca4202  rfl: 0x0000000000010202  cr2: 0x0000000103f1a010
  
Logical CPU:     3
Error Code:      0x00000004
Trap Number:     14


Binary Images:
    0x7fff6bca3000 -     0x7fff6bcdaa47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 120076
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=308K resident=0K(0%) swapped_out_or_unallocated=308K(100%)
Writable regions: Total=10.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=10.2M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Process Corpse Info               2048K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                             240K        3 
__LINKEDIT                          84K        2 
__TEXT                             224K        2 
mapped file                         20K        4 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             66.6M       13 

Model: Macmini6,1, BootROM MM61.0106.B0A, 2 processors, Intel Core i5, 2.5 GHz, 16 GB, SMC 2.7f1
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1333 MHz, 0x029E, 0x434D5341384758334D314131333333433920
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1333 MHz, 0x029E, 0x434D5341384758334D314131333333433920
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x10E), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Samsung SSD 840 EVO 250GB, 250.06 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB2.0 Hub
USB Device: USB Receiver
USB Device: Usb production
USB Device: irDAC II
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: iPad
USB Device: iPhone
USB Device: Ergodox
Thunderbolt Bus: Mac mini, Apple Inc., 23.4
```

**Comment by JessThrysoee** [comment]
I admit, I have only testet `codesign --remove-signature` on macOS 10.12

**Comment by jmoody** [comment]
I can confirm that this fix works.

* Xcode 8 released
* Sierra GM

**Comment by hnguyen94** [comment]
It does not work on  El Capitan :(

**Comment by DorianListens** [comment]
I can also confirm that this works fine with Xcode 8 GM on Sierra GM

**Comment by jamapag** [comment]
Works for me perfectly with EL Capitan 10.11.6, and Xcode release version.

**Comment by JugglerShu** [comment]
`codesign` didn't support `--remove-signature` but it seems El Capitan version supports it. I'll test it and merge. Thanks.

**Comment by JugglerShu** [comment]
My codesign tool doesn't work with --remove-signature option... It may require update to Sierra...

**Pull request closed without merging**
