### PR TITLE
Fixed #791 XVim menu not appearing in Editor menu

### LINKED ISSUE #791: XVim Menu Item Disappears in Xcode 6.4
Hi, the menu item XVim disappears in 6.4, so I cannot find a way to disable XVim temporarily.  

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24487645-xvim-menu-item-disappears-in-xcode-6-4?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #803: Missing `XVim` menu item in Xcode 6.4
I have issues where XVim sometimes stops working so I have to run `make` again. Anyways the menu item never reappeared in 6.4. What's the status on that? Thanks.
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25535625-missing-xvim-menu-item-in-xcode-6-4?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F252770&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wczekalski**
Fixes #803 and #791

It should work for all supported Xcode versions

### CODE REVIEW

**Comment by samson333** [comment]
It persists for me and I am using XCode 6.4.

**Comment by wczekalski** [comment]
@samson333 Are you sure you checked out my branch? I won't say I'm sure it should work (you never know with Xcode) but it looks like it should. Please clone [wczekalski/XVim](https://github.com/wczekalski/XVim) and checkout `fix/#791-6.4-Menu-Item`. If you are sure it doesn't work, well, then let's close this issue :disappointed:

**Comment by samson333** [comment]
Wow. It is back. I tried uninstall and install for a few times. Then I gave up. But after rebooting, it is back... Looks like need to reboot.

**Comment by davidquon** [comment]
Unfortunately this is still a problem for me.  I'm using OSX Yosemite 10.10.4 with Xcode Version 6.4 (6E35b).  I'm on the `develop` branch of XVim with these changes and have tried rebooting the computer and closing and reopening Xcode numerous times.  If I install XVim with Xcode open the menu will show up but XVim won't work.  If I then close and open Xcode the menu will be gone.

**Comment by samson333** [comment]
Did you try clone and download from this branch:

https://github.com/wczekalski/XVim/tree/fix/%23791-6.4-Menu-Item.

Best regards,
Tian

**Comment by davidquon** [comment]
After upgrading to OSX `10.10.5` and pulling the latest `develop` branch on commit `d5ef953` it's now working for me.  :+1:

**Comment by wczekalski** [comment]
To all early adopters: Please make sure that you install from `XVimProject:develop`. This code is not conatined in the `master` branch AFAIK. If you are sure you cloned from the branch **and** restarted Xcode and the menu still doesn't show up, then there's something wrong going on and this problem should be revised.

**Pull request merged**
