### PR TITLE
improve Pluginuuid relating tool

### PR DESCRIPTION
**Pull request by pebble8888**

### CODE REVIEW

**Comment by MikeSilvis** [comment]
This looks helpful. Can we merge it?

**Comment by atomkirk** [comment]
Agreed. Can we please merge this? @JugglerShu 

I just tried this and it works great:

(make sure you have the `plist` gem installed: `gem install plist --no-rdoc --no-ri`)

```bash
rake updatepluginuuid
make
```

**Comment by MikeSilvis** [comment]
@atomkirk yeah, the plist gem should really be added to the Gemfile

**Comment by atomkirk** [comment]
True. I didn't even think of running `bundle install` ;)

**Comment by pebble8888** [comment]
@atomkirk
Thanks for your indication.
No problem for adding it.

**Comment by JugglerShu** [comment]
@pebble8888 
Can you add a description how to use this in somewhere in Readme.md ?

**Comment by pebble8888** [comment]
I added a description.
I don't know DOCTYPE modification should merge to XVim repo.
A new DOCTYPE support pull request posted in plist gem, but 
there is no hope that PR is merged.

**Comment by JugglerShu** [comment]
Thanks!

**Pull request merged**
