### PR TITLE
Add support for inverting set options

### PR DESCRIPTION
**Pull request by squarefrog**
This patch adds support for inverting set options. For example, in vim, you may use:

    :set rnu!

to toggle between `:set relativenumber` and `:set norelativenumber`.

I don't see a test case for options so I can't write a test case. I can confirm the following manual tests:

    :set rn!               # sets relative number on
    :set rn!               # sets relative number off
    :set relativenumber!   # sets relative number on
    :set relativenumber!   # sets relative number off
    :set bc!               # sets blinking cursor on
    :set bc!               # sets blinking cursor off
    :set clipboard!        # does nothing as `_clipboard` is not a `BOOL`
    :set !                 # does nothing

### CODE REVIEW

**Comment by JugglerShu** [comment]
Thank you for the PR. Yea, I need the test cases. You can add XVimTester+Options category if you need. Follow the methods written in existing test case file like XVimTester+Motion.m .

**Comment by squarefrog** [comment]
But this doesn't affect motion. It affects changes with the `:set` method.

**Comment by JugglerShu** [comment]
So you can create XVimTester+Options.m file .

**Comment by squarefrog** [comment]
I understand how XVimTester works, but I don't see it will be useful in this case. Setting options doesn't affect text or cursor position.  

I can write a standard XCTest file for this behaviour though, if you would prefer this. However I don't know that this will get run with all the motion tests

**Comment by JugglerShu** [comment]
Some test cases can be tested like `[no]ignorecase`. You can write command that searches in case sensitive or incase-sensitive and then put `[no]ignorecase` then search again. The resulted cursor position can be tested.
For UI related options you don't need to write.

**Comment by squarefrog** [comment]
Ok good idea :+1: I'll add that tomorrow.

**Comment by squarefrog** [comment]
@JugglerShu I have added a test runner

**Comment by JugglerShu** [comment]
Please let me ask you one more thing.
Please write a test case for an option that shouldn't take inversion.
This test case should test `strcmp([oldValue objCType], @encode(BOOL)) == 0` part.
Any options are fine. Maybe the result is just nothing happen.

**Comment by squarefrog** [comment]
I can do, but it seems like a bit of a pointless test. What are you actually wanting to test here?

**Comment by JugglerShu** [comment]
Yes. With the test we can keep such invalid operation doesn't make crash or anything.

**Comment by squarefrog** [comment]
There you go :+1:

**Pull request merged**
