### PR TITLE
Add Xcode 7.1 UUID

### PR DESCRIPTION
**Pull request by kaishin**

### CODE REVIEW

**Comment by kaishin** [comment]
Just realized it's a dupe of #850 closing

**Comment by neybis** [comment]
@kaishin, I apologize for asking this here. I've been trying to figure out how I can contribute to this project and had a quick question. I've asked in a few different places but haven't gotten an answer and the issue still seems unresolved.

*Am I the only one that can't build develop at 125c207a73d9f7584d52c2b6bd217f17ef327e20??*

I have, like, 5 pull requests I want to submit, but I have not been able to test them against head of develop because it won't build. I assumed testing against head was a requirement submitting a pull request...

I've been trying to figure out why head is failing but to no avail. I'm still familiarizing myself with the codebase; hopefully, some of the community here will be willing to help me out and answer some of my questions when I have them so I can learn more and contribute to a plug-in that will help me out so much moving forward.

**Comment by kaishin** [comment]
@neybis I am able to build post that commit. Did you open an issue for that with more details about the error you are getting?

**Comment by neybis** [comment]
Nope, I just commented on the commit itself. I'm running Xcode 6.1. Thank you for your response. I'll open up an issue :)

**Pull request closed without merging**
