### PR TITLE
Xcode8: fix relative line numbers

### PR DESCRIPTION
**Pull request by antmd**
Hi,

I fixed relative number for Xvim on Xcode8. I think it should be backward compatible with Xcode7, but I can't test as I don't have Xcode7.

This is a pull request against 'master', because that's the only branch that contains the updates for Xcode8 at the moment.

Feel free to reject until it is decided what to do with the Xcode8 changes. I can see the alternatives:

a) rolling Xcode8 changes into develop, so I can put my changes there
b) creating new 'xcode8' branch from before first Xcode8 change on master, then reverting the changes on master

I favour b) : it won't cause 'branch explosion', as the rate of commits is quite small at the moment, and as Xcode8 now makes things a lot harder for plugin authors, it might be worth keeping 'master' 'clean' until we have a better story for continued development.

Best Regards
--Anthony

### CODE REVIEW

**Comment by Goles** [comment]
@JugglerShu This one seems rather important and looks good. What are your thoughts?

**Comment by JugglerShu** [comment]
Sorry I haven't checked this yet.
But one thing at least to say. Why does it have a header file in the root directory of the XVim?

**Comment by Goles** [comment]
looking at that too @JugglerShu , to be honest, it's not evident to me. @antmd thoughts on that?

**Comment by antmd** [comment]
Yes, @Goles @JugglerShu that file was a mistake. I've deleted it. Looking at my change critically, I wonder if it would have been better to use a runtime check for Xcode8/7 instead of a compile-time check. The problem with a compile-time check is that if we distribute pre-built packages, then we'd need two different packages...on the positive side, I'm not a fan of lots of 'respondsToSelector:' calls...but I can understand why they might be more practical. So, I can re-work this to use run-time checks, if necessary. Best, --Anthony

**Pull request merged**
