### PR TITLE
Normal mode playground cursor enabled 🎉

### PR DESCRIPTION
**Pull request by theyongdai**
screen shot 2016-11-16 at 9 52 52 pm

// Copypasta from pebble8888/XVim, Huge thanks to pebble8888!!
// Here's the link to the commit:
// https://github.com/pebble8888/XVim/commit/e27a614f6b59534b934ddeecba4c7355f34d4057

### CODE REVIEW

**Comment by tflhyl** [comment]
+1 for this, ive been using the commit and it works perfectly

**Comment by idrisr** [comment]
+1000 for this. just tried it and it works and it just made my day.

**Comment by WANGjieJacques** [comment]
please merge this commit.

**Comment by theyongdai** [comment]
image

**Comment by JugglerShu** [comment]
This is merged into Develop branch.
I'm working on merging this to master but it still needs some fixes.

**Comment by jaabio** [comment]
I'm looking forward to being able to use Xvim in playgrounds once this is merged into master.

**Comment by hitzhangjie** [comment]
I am using XCode 8.2.1, I come across the same issue, but after I "git check develop ; make uninstall ; make", the cursor in normal mode in playground comes back!
Please try this 'develop' branch.

**Comment by theyongdai** [comment]
The good, bad and ugly of open source.. Don't worry, just use the `develop` branch for that one particular feature.

**Pull request closed without merging**
